### ISSUE TITLE
Add link for recall

### ISSUE THREAD

**Issue by Chaostheorie** [kallisti5/chevybolt#1]
See [official recall by NHTSA (US)](https://www.nhtsa.gov/press-releases/consumer-alert-important-chevrolet-bolt-recall-fire-risk). Cause the chevy's too hot for the consumer. Might be useful for anyone searching this repository later on.

**Comment by kallisti5** [comment]
yeah, I probably should lay out the whole recall history in general here.  other places like allev.info cover individual fires better though.

**Comment by kallisti5** [comment]
I added a pretty large section on the recall mentioning the NHTSA recall ID's. Their site is kind of a mess so i'm not linking directly to it.

**Comment by Chaostheorie** [comment]
Thank you for the Addition oft the recall to your project. Good luck with your bolt
-----------------------------------
Cobalt
w: https://cobalt.rocks
e: ***@***.***
